# Generated by Django 4.1 on 2022-09-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_alter_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50, verbose_name='name')),
                ('contact_email', models.EmailField(max_length=100, verbose_name='email')),
                ('contact_message', models.CharField(max_length=250, verbose_name='message')),
            ],
        ),
    ]
