# Generated by Django 4.1 on 2022-09-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
