# Generated by Django 4.1.7 on 2023-07-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0012_alter_comment_id_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Başlık'),
        ),
    ]
